### ISSUE TITLE
Support User defined Github URL for Github Enterprise users

### ISSUE THREAD

**Issue by dennisgove** [menubar-apps/PullBar#12]
It'd be nice if one of the user options allowed setting the [base URL](https://github.com/menubar-apps/PullBar/blob/57487297490a767f36fda22d7bf76c1d81331863/pullBar/GitHub/GitHubClient.swift#L37). This would allow people to use this against with an on-prem Github Enterprise installation.

**Comment by dennisgove** [comment]
I'm happy to work on a PR if you're open to this feature.

**Comment by streetturtle** [comment]
That would be awesome! Thanks!

**Comment by streetturtle** [comment]
I've just added this feature, sorry for a delay :)
It's live in github releases and a brew. Waiting for App Store to review the new version.
