### ISSUE TITLE
Show PR status, i.e draft, ready to merge, closed

### ISSUE THREAD

**Issue by streetturtle** [menubar-apps/PullBar#15]
Show PR status, i.e draft, ready to merge, closed.

**Comment by marwanhawari** [comment]
Made a PR here https://github.com/menubar-apps/PullBar/pull/18 to display if a PR is a draft or not.

**Comment by streetturtle** [comment]
@marwanhawari thanks! I've changed a UI slightly - now it's a dot in from of a PR title.
