### ISSUE TITLE
Installation link in README broken

### ISSUE THREAD

**Issue by tomdaly** [menubar-apps/PullBar#16]
Hi @streetturtle, thanks for developing this app! It's not only really useful to keep track of my assigned/created PRs, but it looks great too.

I noticed one problem when first installing - the text 'Download and install the latest release' in the [README](https://github.com/menubar-apps/PullBar#installation) 404s. 

I was going to submit a PR to change the URL to `https://github.com/menubar-apps/PullBar/releases/latest/download/pullbar.dmg` (from [this guide](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases)) but it looks like that link only works if the asset name is the same across all releases. 

I think for that to work you'd have to change the release asset from `pullbar.<version>.dmg` to `pullbar.dmg` or link straight to the GitHub 'latest releases' page (https://github.com/menubar-apps/PullBar/releases/latest) and let users download the latest `.dmg` from there.

**Comment by streetturtle** [comment]
Thanks for looking into this! I think I'll be updating readme with each release manually for now, as the version in the file name could be useful in some cases.
