### ISSUE TITLE
Support `Commit Statuses`

### ISSUE THREAD

**Issue by gondalez** [menubar-apps/PullBar#19]
A repo I work on is configured to use [`Commit Statuses`](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28) (not [`Checks`](https://docs.github.com/en/rest/checks?apiVersion=2022-11-28)).

PullBar supports `Checks` only, which means I don't see any of the cool little colourful dots:

![CleanShot 2023-04-24 at 17 00 37@2x](https://user-images.githubusercontent.com/1468141/233950196-fde2abe4-9985-4203-8d1a-fb1f0a45c184.png)

I would love it if it also supported `Commit Statuses` and showed colourful dots for each status :) 🙏 
Much like the demo from the readme:

![CleanShot 2023-04-24 at 17 03 00@2x](https://user-images.githubusercontent.com/1468141/233950470-0134289d-8370-4d73-8ebf-62ac71780722.png)

**Comment by streetturtle** [comment]
Very good point! I'll definitely add an option to chose between Commit Statuses and Checks.
