### ISSUE TITLE
On-demand refresh

### ISSUE THREAD

**Issue by gondalez** [menubar-apps/PullBar#20]
I find I nearly always want to run a refresh when I open the callout.

Given the tray icon doesn't show a count, could it work to replace the manual and periodic refresh with the following?

- Start a refresh when the mouse goes over the tray icon (or even when it is clicked)
- On the callout, show a refresh state with a spinner while refreshing

**Comment by streetturtle** [comment]
Hi! Thank you for the issue!

I agree with this FOMO feeling when the menu is opened, but the more I work with the menus, the more I realize that it wasn't built for dynamic content, like loading animation, or partilal redraw. Updating the menu when the icon is clicked might give a delay (up to a 2 seconds in case of a private repo) during which the menu should be locked from user interactions, as it might break the menu. 

I'll try to play a bit more with it, maybe I'll find a better way of updating the menu.

**Comment by gondalez** [comment]
Thanks @streetturtle 🙏 

I've never worked on a tray menu project before. It sounds constrained from what you say. 
Constraint can be kinda fun for the creative side perhaps? :)

I'm not sure if you have access to mouse-over events, but triggering the load when the user puts their mouse over the icon before clicking it might be a sneaky way shave some msecs off the wait time 🤔

**Comment by streetturtle** [comment]
Hey @gondalez 👋 
I have created a better version of the PullBar (I hope you still use it 😄). It uses another UI approach - SwiftUI instead of menu, which solves all the menu-related issues (closes on click, dynamic content, etc). 

I would really appreciate if you can test it and share your feedback. Here is a link for a [14-days trial version](https://github.com/menubar-apps/PullBarPro/releases).

**Comment by gondalez** [comment]
Thanks @streetturtle I have installed it and so far it works great!
I like the refresh indicator and also the callout for the list of status checks 🙏 

I'll let you know how I find it over the coming weeks :)

**Comment by gondalez** [comment]
Hi @streetturtle,

I've been using and liking it since ^ and I have upgraded to pro :) ✨ 

I have a few feature requests:

* it'd be nice to highlight the PR row when hovering the mouse pointer
* when I click some empty spaces in the PR row it doesn't open the PR
* when I upgraded to pro from the trial version the _api base url_ and _username_ fields had "expired trial" in them and I had to fill them in with the right values manually

**Comment by streetturtle** [comment]
Thank you for trying it out and being an early adopter! 👍 I really appreciate it!

I've released a new version which adds the row highlighting. Regarding your second point, the whole row is acting as a button/link, except the review and checks menus. Could you please check again. 
And I'll update the trial version to keep existing values when switching to the full version. 
Thanks again 👍

**Comment by gondalez** [comment]
@streetturtle no worries at all, thanks for the handy tool 🙏 :)

Will the new version make it to the App Store eventually?

For the clicking issue, here is a repro of the bug:

![CleanShot 2023-10-06 at 13 50 08](https://github.com/menubar-apps/PullBar/assets/1468141/87b09781-627e-4f4a-b67f-6f62a4d5c042)

**Comment by streetturtle** [comment]
Interesting, this looks like a previous version. Have you recieved an update - the version 1.2?

**Comment by gondalez** [comment]
@streetturtle I got the new version and tried it, can confirm it is fixed now. Thanks :)
