### ISSUE TITLE
new advanced tab does not work

### ISSUE THREAD

**Issue by jupe** [menubar-apps/PullBar#32]
# Describe the bug
once you try to select advanced filter, app goes to Authentication tab and you can't navigate anymore to any other tab.

Installed with homebrew.

Related to PR: #14 #29 

# How To Reproduce
1. Go to Preferences
2. Click on Advanced tab
3. Click Query textbox
4. Preferences dialog is stuck on Authentication tab

CC: @owenrumney

**Comment by owenrumney** [comment]
FWIW, I've not been able to reproduce this. I installed entirely fresh of the latest version and the advanced tab worked okay. Would be interesting to see a screenshot, I don't have a config tab so that's puzzling me a little too

**Comment by jupe** [comment]
Record below I first played with other tabs, which seems to work okay, but in the end I open advanced tab and clicked edit box where I would put my custom query, but then whole dialog stuck to Authentication tab. I've macOS 15.1 .
![pullBar](https://github.com/user-attachments/assets/146b168e-cfab-40c6-8bb5-6c59065751bd)

Other weird behaviour was that when clicking General tab checkbox, it jump to Authentication tab that was unexpected. That's also visible in above gif.

**Comment by streetturtle** [comment]
I believe it is related to the new macOS version - I've seen this behavior in another app. I'm currently still on Sonoma on my main mac - and it works without any problem. 

I'll upgrade to Sequoia and will investigate this issue.
Thank you for raising it! I'll keep you posted.

**Comment by jupe** [comment]
Indeed, whole thing sounds weird and fully unexpected behavuour. I didn’t even found single codeline that would change tab, so most probably it related to some framework/Sequoia. Did you used latest xcode to build app?

**Comment by jupe** [comment]
By the way, where app stores configs? Could I manually edit custom query as a workaround?

**Comment by streetturtle** [comment]
I think the issue should be fixed by #33. 
Can you test the pre-release: https://github.com/menubar-apps/PullBar/releases/tag/v1.11, please.

**Comment by jupe** [comment]
that seems to fix this issue. Thanks! 👍
