### ISSUE TITLE
No PR's returned

### ISSUE THREAD

**Issue by jeffutter** [menubar-apps/PullBar#34]
Lately, PullBar hasn't been returning any PRs for me. I've checked that the token has access. I've also tried the custom query in the advanced tab on `1.11`. The same query in the github web application returns 12 tickets, but PullBar returns nothing.

Are there logs anywhere such that I can inspect what it's doing and see if there are any errors?

**Comment by alvarovillafane** [comment]
I got pull bar pro and having the same issue

**Comment by streetturtle** [comment]
@jeffutter what kind of token are you using? A classic one, or a fine-grained?

**Comment by jeffutter** [comment]
@streetturtle i actually don’t recall (and apparently I didn’t name the tokens terribly well 😁). I can definitely try recreating a new token. If I use fine-grained- is there a list of permissions it should have?

**Comment by streetturtle** [comment]
So the the fine-grained token you will need to have **Contents** and **Metadata** permissions. For the classic one you need just a **repo** scope. 

Maybe your token just got expired?

**Comment by jeffutter** [comment]
I regenerated the tokens and things still didn't work. I then removed the `Advanced > Adidiontal Query` and _some_ PRs popped up.

FWIW I think my work has 3 github orgs (we'll call them `org1`, `org2`, `org3`). `org1` is older and may not have SSO the other two do. When it loads anything it loads 13 PRs, all from `org1` and are irrelevant to me. I am _sure_ I have authorized `sso` on the token in use (trying a classic token for now) for both `org2` and `org3`.

Fwiw, the advanced query I'm using that returns nothing is:

```
is:open is:pr org:<org2> org:<org3> review-requested:jeffutter
```

When I paste that same query into https://github.com/search it returns 17 PRs.

**Comment by jeffutter** [comment]
Ok. I managed to sort this out. Fine grained tokens only apply to repos based on their "owner". I could create a fine-grained token within my work org, but it would require requesting access from an admin. If I make the token under my name it only has access to my own repos.

Classic tokens don't have this issue. So those seem to work OK.
